Adding Always-Free tier singup to start
oracle-devrel/redbull-analytics-hol pull request #7
Opened 2021-07-21 20:36 UTC by GreatGhostsss

Without creating an account, attendees won't be able to create a stack, etc. Added section: "Sign up for an Always-Free tier OCI account"

2021-07-22 18:28 UTC, GreatGhostsss commented
I have read the CLA Document and I hereby sign the CLA

2021-07-23 07:58 UTC, snafuz requested changes
Please change the URL

2021-07-23 07:58 UTC, snafuz commented on terraform/README.md
> +1. Visit the [Oracle Cloud Free Tier](https://signup.cloud.oracle.com/?sourceType=_ref_coc-asset-opcSignIn&language=en_US) page.
Please change the URL

2021-07-23 13:57 UTC, timclegg approved these changes

2021-07-26 16:41 UTC, snafuz approved these changes

2021-07-26 16:41 UTC, merged